<?php

namespace ZymerCartBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends \Doctrine\ORM\EntityRepository
{
    public function listEmployee($id='')
    {
        
        $query=$this->createQueryBuilder('emp');
        $query->select();
        if($id)
        {
            $query->where("emp.empid = :eid");
            $query->setParameter('eid', $id);
        }
        return $query->getQuery()->getArrayResult();
        
    }
    public function addEmployee($data)
    {
        $this->getEntityManager()->persist($data);
        $this->getEntityManager()->flush();
        return $data;
    }
    public function editEmployee($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $data;
    }
}
